### ISSUE TITLE
custom wait problems

### ISSUE THREAD

**Issue by ImpostorMan** [PysephRBX/RBXWait#1]
there are so many things wrong with this. I don't sound mean but firstly, just don't yield. let me explain more in depth. Yielding would require you to create extra coroutines and coroutines are simulated multi threading. why? because lua is a single threaded language. nothing can **TRUELY** be ran at the same time since it's all on the same thread. using coroutines would slow down your game substantially because of that.

Using a priority queue to resume a thread. another major error that you made. since each frame is being checked at o(1), there's no way to resume multiple threads in one second so the only use that i can think of for this which is using it in while true loops, is completely basically useless since you can only use one while loop with your custom wait. in fact, it's 10x better to make a call frames module and connect to that and do a while loop instead of calling a function each iteration to wait.

Now in conclusion, avoid waits. Your implementation is basically useless.

**Comment by PysephRBX** [comment]
Hello, if you believe there is an issue with the script then please provide a repro showcasing this issue.
I am well aware of the fact that Lua is not multi-threaded and simulates it through coroutines, no need to educate me just to act like the smarter person in the room. Your arrogance is unneeded here.

> Using a priority queue to resume a thread. another major error that you made. since each frame is being checked at o(1), there's no way to resume multiple threads in one second

I have already addressed this issue by looping through all the yields - for every Stepped call, I get the first yield in the queue, check if it has already yielded, and if it has, I unyield it, remove it from the loop, get the new yield, do the same checks and repeat.

> is completely basically useless since you can only use one while loop with your custom wait.

And how is this useless? In fact, it is even better for performance because you only need to utilize one loop to update several yields.

This implementation is far from useless. If you want an example of how useful this script is, be sure to check out https://twitter.com/CloneTeee1019/status/1264764207498657792.
Other than that I will be closing this conversation as you are not experiencing any issues, rather you are just ranting about how bad this script is. If you wish to hold a proper conversation, feel free to contact me on Discord: Pyseph#1015.
Have a good day.
